---
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: End-to-End (E2E) Tests
jobs:
  e2e:
    strategy:
      fail-fast: true
      matrix:
        kubernetes:
          - v1.23.10
      max-parallel: 2
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
          cache: true
          check-latest: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ matrix.kubernetes }}

      - name: Create KinD cluster
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.15.0
          node_image: kindest/node:${{ matrix.kubernetes }}
          cluster_name: kind
          config: test/kind/config.yaml
          wait: 120s

      - name: Verify KinD cluster
        run: make verify-kind

      - name: Install Registry
        run: make install-registry

      - name: Add cluster hosted registry name to /etc/hosts
        run: echo "127.0.0.1 registry.registry.svc.cluster.local" | sudo tee -a /etc/hosts

      - name: Installing Shipwright Build Controller
        run: make install-shipwright

      - name: Build Application (shp)
        run: make build

      - name: End-to-End Tests
        run: make test-e2e
